package ru.banana.andrew.gameroom;

/**
 * Created by С новым годом!!! on 15.01.2017.
 */

public class DataBase {

    public static Videogame GTAV = new Videogame("Grand Theft Auto — мультиплатформенная видеоигра в жанре action и «открытый мир», разработанная компанией Rockstar North и изданная компанией Rockstar Games.", "http://cdn.images.express.co.uk/img/dynamic/143/590x/GTA-5-Update-616242.jpg", "http://www.gtafans.ru/sites/default/files/imagepicker/1/gta-5-screenshots-36.jpg", "Grand Theft Auto", "https://img.gta5-mods.com/q95/images/ford-mustang-1965-hoonicorn-add-on/e868af-GTA5%202016-04-16%2019-26-14-88.jpg", "http://static1.gamespot.com/uploads/original/123/1239113/2861382-gta5.jpg", "https://github.com/ivanoff0a/A/raw/0f0e4bec8ff21e90e25c8ad023e69379da6ff62c/temp/GTA%205%20-%20Trailer.mp4");
    public static Videogame BATTLEFIELD1 = new Videogame("Battlefield — мультиплатформенная компьютерная игра в жанре шутера от первого лица, разрабатываемая компанией DICE и издаваемая Electronic Arts для платформ Windows, PlayStation 4 и Xbox One", "http://orig14.deviantart.net/1577/f/2013/099/f/b/battlefield_logo_by_misculos-d6106h3.jpg", "https://content.pulse.ea.com/content/battlefield-portal/ru_RU/news/battlefield-1/road-to-battlefield-stream/_jcr_content/featuredImage/renditions/rendition1.img.jpg", "Battlefield", "https://data2.origin.com/live/content/dam/originx/web/app/games/battlefield/battlefield-1/screenshots/battlefield-1/BF1_se_screenhi_930x524_en_US_behemoth_v1.jpg", "https://content.pulse.ea.com/content/battlefield-portal/en_US/news/battlefield-1/the-single-player-of-battlefield-1/_jcr_content/featuredImage/renditions/rendition1.img.jpg", "https://github.com/ivanoff0a/A/raw/2e6957a8845b090f60a4bf9d56a6a51f31240739/temp/Battlefield%201%20Official%20Gameplay%20Trailer.mp4");
    public static Videogame UNCH = new Videogame("Uncharted — серия компьютерных игр в жанре action-adventure, разработанных компанией Naughty Dog и изданных Sony Computer Entertainment для консолей PlayStation.", "http://www.allkeyshop.com/blog/wp-content/uploads/uncharted_4_banner.jpg", "http://uwrena.ru/wp-content/uploads/2016/05/93vxrh1u.jpg", "Uncharted", "https//virtualgameinfo.ru/wp-content/uploads/2016/05/Uncharted-4-brothers-adventure-last-drake.jpeg", "https://i.kinja-img.com/gawker-media/image/upload/s---0e1tU1k--/c_scale,f_auto,fl_progressive,q_80,w_800/tit8ia9em5b8meb5pz4t.png", "https://github.com/ivanoff0a/A/raw/2e6957a8845b090f60a4bf9d56a6a51f31240739/temp/UNCHARTED%204_%20A%20Thief's%20End%20(5_10_2016)%20-%20Story%20Trailer%20_%20PS4.mp4");
    public static Videogame MEC = new Videogame("Mirror’s Edge — кроссплатформенная компьютерная игра в жанре приключенческого боевика и платформера от первого лица, разрабатываемая компанией DICE под издательством Electronic Arts", "http://www.logodesignblog.net/logos/mirrors-edge-logo.jpg", "http://www.straight.com/files/v3/images/15/06/eai9dmaeudbz.878x0.z-z96kyq.jpg", "Mirorr's Edge", "https://cdn0.vox-cdn.com/thumbor/b03uJ3qJzCY_ZjOcysUasxvLMCQ=/cdn0.vox-cdn.com/uploads/chorus_asset/file/6599375/Mirrors-edge-catalyst_Launch_Screen_06_BlackNovember_WM.0.jpg", "http://gearburn.sndytsvoxozgokstuvcm.netdna-cdn.com/wp-content/uploads/2016/08/Mirrors-Edge-Catalyst-review-6.jpg", "https://github.com/ivanoff0a/A/raw/2e6957a8845b090f60a4bf9d56a6a51f31240739/temp/Mirror%E2%80%99s%20Edge%20Catalyst%20Story%20Trailer%20%E2%80%93%20I%20Am%20Faith.mp4");
    public static Videogame W_D = new Videogame("Watch Dogs — мультиплатформенная компьютерная игра в жанре приключенческого боевика с открытым миром.Играя за хакера Вам предстоит взломать весь город и подчинить его себе.Игра была разработана компанией Ubisoft.", "https://jbhnews.com/wp-content/uploads/2016/11/watch-dogs-2-600x338.jpg", "http://assets1.ignimgs.com/thumbs/userUploaded/2016/6/8/watchdogsthumb2-1465405447883_large.jpg", "Watch_Dogs", "https://alogvinov.com/wp-content/uploads/2016/10/Watch-Dogs-2.jpg", "http://www.game-ost.ru/static/content/2016/11/09/4952_715327.jpg", "https://github.com/ivanoff0a/A/raw/2e6957a8845b090f60a4bf9d56a6a51f31240739/temp/Watch%20Dogs%202%20-%20%D0%A2%D0%B5%D0%BB%D0%B5%D0%B2%D0%B8%D0%B7%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9%20%D1%82%D1%80%D0%B5%D0%B9%D0%BB%D0%B5%D1%80.mp4");
    public static Videogame A_C = new Videogame("Assassin’s Creed (с англ. — «Кредо ассасина») — серия мультиплатформенных компьютерных игр в жанре приключенческого боевика, разработанная компанией Ubisoft Montreal для PlayStation 3, PlayStation 4, Xbox 360, Xbox One, Windows и других. Игра издается французской компанией Ubisoft.", "http://cdn.inquisitr.com/wp-content/uploads/2016/07/Assassins-Creed-collection-Ubisoft-troll.jpg", "http://cdn.mos.cms.futurecdn.net/28f0cbcfde82dc9dcf1b041c837677e0.jpg", "Assasin's Creed", "https://ubistatic9-a.akamaihd.net/resource/ru-RU/game/assassins-creed/ac/acu-gi-02_147186.jpg", "http://s50.radikal.ru/i130/1311/0e/ed32e88a192b.jpg", "");
    public static Videogame C_O_D = new Videogame("Call of Duty — серия компьютерных игр в жанре шутера от первого лица, посвящённых Второй мировой войне, холодной войне, борьбе с терроризмом и гипотетической Третьей мировой войне.", "http://kodotel.ru/wp-content/uploads/2016/10/call-of-duty.jpg", "https://xage.ru/media/posts/2014/5/5/its-all-about-call-of-duty-advanced-warfare_3.jpg", "Call Of Duty", "http://www.gamedeus.ru/images/games/C/call-of-duty-modern-warfare-remastered/call-of-duty-modern-warfare-remastered-01.JPG", "https://psmedia.playstation.com/is/image/psmedia/call-of-duty-ghosts-screen-01-ps4-eu-03nov14?$MediaCarousel_Original$", "");
    public static Videogame F_H = new Videogame("For Honor — компьютерная игра в жанре hack and slash, разрабатываемая канадской компанией Ubisoft Montreal для Microsoft Windows, PlayStation 4 и Xbox One.", "https://i.ytimg.com/vi/sp3NKQlJPuo/maxresdefault.jpg", "http://static1.gamespot.com/uploads/original/1547/15470456/3110647-91o6fdzdtwl._sl1500_.jpg", "For Honor", "http://blog.ubi.com/app/uploads/2016/08/fh_screen_warden_vs_orochi_gc_160817_920am_1471354583.jpg", "https://ubistatic9-a.akamaihd.net/ubicomstatic/en-US/global/media/FH-screenshot-03-FULL_255363.jpg", "");
    public static Videogame U_D = new Videogame("Until Dawn — консольная игра в жанре интерактивное кино с элементами survival horror, разработанная компанией Supermassive Games исключительно для игровой приставки PlayStation 4. Издатель игры — Sony Computer Entertainment. ", "https://media.playstation.com/is/image/SCEA/until-dawn-listing-thumb-01-us-12aug14?$Icon$","https://cdn3.vox-cdn.com/uploads/chorus_asset/file/3994470/until_dawn_review_b_1920.0.jpg", "Until Dawn", "https://cdn.techinasia.com/wp-content/uploads/2014/09/close-up-man-until-dawn.jpg","http://kronikum.com/wp-content/uploads/2014/08/Until-Dawn1.jpg","");
    public static Videogame R_S = new Videogame("Tom Clancy’s Rainbow Six  — тактический шутер от первого лица, разработанный Ubisoft для Microsoft Windows, Xbox One и PlayStation 4. ", "http://wallpapersdsc.net/wp-content/uploads/2015/10/Rainbow_Six_Siege_26.jpg", "https://ubistatic9-a.akamaihd.net/ubicomstatic/en-US/global/media/R6S-screenshot-new_4_199582.jpg", "Tom Clancy's: Rainbow Six", "https://www.instant-gaming.com/images/products/406/screenshot/406-4.jpg","https://ubistatic19-a.akamaihd.net/resource/en-US/game/rainbow6/siege/SixInvitational_KeyArt_01_277352.png","");
    public static Videogame DRIVER = new Videogame("Driver — серия видеоигр в жанре автосимулятор и 3D шутер, с «открытым игровым миром», где игрок может свободно перемещаться по городу.","http://i0.wp.com/half-empty.net/wp-content/uploads/2014/01/logo.jpg","http://cdn.gameslikefinder.com/wp-content/uploads/driver-san-francisco-gameplay2.jpg", "Driver","http://www.retropelit.fi/wp-content/uploads/2012/09/Driver02.jpg","https://www.daily2soft.com/wp-content/uploads/2016/08/Driver-San-Francisco-PC-Game-Crack-Download-Daily2soft1.jpg","");


    public static Videogame[] ГАМЫ = new Videogame[]{GTAV, BATTLEFIELD1,UNCH,MEC,W_D,A_C,C_O_D,F_H,U_D,R_S,DRIVER};
}
